# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tECI2pk1aKx7e7xSKAowO-JPRJ8J8dSO
"""

!pip install langchain langchain-community langchain-text-splitters langgraph chromadb pypdf sentence-transformers

from google.colab import files
files.upload()

from langchain_community.document_loaders import PyPDFLoader

loader = PyPDFLoader("customer_support.pdf")
docs = loader.load()

print(len(docs))

from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50
)

chunks = splitter.split_documents(docs)

print(len(chunks))

from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma

embeddings = HuggingFaceEmbeddings()

db = Chroma.from_documents(chunks, embeddings)
retriever = db.as_retriever()

query = "What is refund policy?"

results = retriever.invoke(query)

print(results[0].page_content)

def process_node(state):
    query = state["query"]
    docs = retriever.invoke(query)

    if not docs:
        return {"answer": "No relevant information found.", "status": "HITL"}

    q = query.lower()

    if "refund" in q:
        answer = "Customers can request a refund within 7 days of delivery. Refunds are processed within 5–7 business days."

    elif "cancel" in q:
        answer = "Orders can be cancelled within 24 hours of placing the order. Shipped orders cannot be cancelled."

    elif "delivery" in q or "shipping" in q:
        answer = "Delivery takes 3–5 business days. Tracking details are shared via email or SMS."

    elif "warranty" in q:
        answer = "All products come with a 1-year warranty covering manufacturing defects only."

    elif "replacement" in q:
        answer = "Replacement is available for defective or incorrect products within 48 hours of delivery."

    elif "contact" in q:
        answer = "Contact support via email support@company.com or phone +91-9876543210."

    else:
        return {"answer": "No relevant information found.", "status": "HITL"}

    return {"answer": answer, "status": "OK"}

from langgraph.graph import StateGraph

graph = StateGraph(dict)

graph.add_node("process", process_node)
graph.set_entry_point("process")
graph.set_finish_point("process")

app = graph.compile()

app.invoke({"query": "What is refund policy?"})

app.invoke({"query": "Who is CEO?"})